# Generated by Django 5.1.1 on 2024-10-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Equity_Status',
            fields=[
            ],
            options={
                'verbose_name': 'Account Equity Status',
                'verbose_name_plural': 'Account Equity Status',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.accountstockconfig',),
        ),
        migrations.CreateModel(
            name='Account_Equity_Transaction',
            fields=[
            ],
            options={
                'verbose_name': 'Account Equity Transaction',
                'verbose_name_plural': 'Account Equity Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.accounttransaction',),
        ),
        migrations.CreateModel(
            name='Account_FnO_Status',
            fields=[
            ],
            options={
                'verbose_name': 'Account FnO Status',
                'verbose_name_plural': 'Account FnO Status',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.accountstockconfig',),
        ),
        migrations.CreateModel(
            name='Account_FnO_Transaction',
            fields=[
            ],
            options={
                'verbose_name': 'Account FnO Transaction',
                'verbose_name_plural': 'Account FnO Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.accounttransaction',),
        ),
    ]
