# Generated by Django 5.1.1 on 2024-10-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_equity_status_account_equity_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountconfiguration',
            name='equity_enabled',
            field=models.BooleanField(default=False, verbose_name='Equity-Enabled'),
        ),
        migrations.AddField(
            model_name='accountconfiguration',
            name='fno_enabled',
            field=models.BooleanField(default=False, verbose_name='FnO-Enabled'),
        ),
    ]
