# Generated by Django 5.1.1 on 2024-10-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_equity_status_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account_Equity_Status',
        ),
        migrations.DeleteModel(
            name='Account_FnO_Status',
        ),
        migrations.CreateModel(
            name='Account_Equity_Entry',
            fields=[
            ],
            options={
                'verbose_name': 'Account Equity Entry',
                'verbose_name_plural': 'Account Equity Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.accountstockconfig',),
        ),
        migrations.CreateModel(
            name='Account_FnO_Entry',
            fields=[
            ],
            options={
                'verbose_name': 'Account FnO Entry',
                'verbose_name_plural': 'Account FnO Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.accountstockconfig',),
        ),
    ]
