# Generated by Django 5.1.1 on 2024-10-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_accountstockconfig_order_placed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountkeys',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
    ]
