# Generated by Django 5.1.1 on 2024-10-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_accountkeys_email'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accountstockconfig',
            index=models.Index(fields=['product'], name='account_acc_product_61f44f_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['product'], name='account_acc_product_7319e7_idx'),
        ),
    ]
