# Generated by Django 5.1.1 on 2024-10-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_accountstockconfig_account_acc_product_61f44f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountconfiguration',
            name='midcpnifty100',
            field=models.BooleanField(default=False, verbose_name='Enable-MidCP100'),
        ),
        migrations.AddField(
            model_name='accountconfiguration',
            name='midcpnifty150',
            field=models.BooleanField(default=False, verbose_name='Enable-MidCP150'),
        ),
        migrations.AddField(
            model_name='accountconfiguration',
            name='midcpnifty50',
            field=models.BooleanField(default=False, verbose_name='Enable-MidCP50'),
        ),
        migrations.AddField(
            model_name='accountconfiguration',
            name='nifty100',
            field=models.BooleanField(default=False, verbose_name='Enable-Nifty100'),
        ),
        migrations.AddField(
            model_name='accountconfiguration',
            name='nifty200',
            field=models.BooleanField(default=False, verbose_name='Enable-Nifty200'),
        ),
        migrations.AddField(
            model_name='accountconfiguration',
            name='nifty50',
            field=models.BooleanField(default=False, verbose_name='Enable-Nifty50'),
        ),
        migrations.AddField(
            model_name='accountconfiguration',
            name='smallcpnifty100',
            field=models.BooleanField(default=False, verbose_name='Enable-SmallCP100'),
        ),
        migrations.AddField(
            model_name='accountconfiguration',
            name='smallcpnifty250',
            field=models.BooleanField(default=False, verbose_name='Enable-SmallCP250'),
        ),
        migrations.AddField(
            model_name='accountconfiguration',
            name='smallcpnifty50',
            field=models.BooleanField(default=False, verbose_name='Enable-SmallCP50'),
        ),
        migrations.AlterField(
            model_name='accountconfiguration',
            name='equity_enabled',
            field=models.BooleanField(default=False, verbose_name='Enabled-Equity'),
        ),
        migrations.AlterField(
            model_name='accountconfiguration',
            name='fno_enabled',
            field=models.BooleanField(default=False, verbose_name='Enabled-FnO'),
        ),
    ]
