# Generated by Django 5.1.1 on 2024-11-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_accountconfiguration_midcpnifty100_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Equity_Portfolio',
            fields=[
            ],
            options={
                'verbose_name': 'Equity Portfolio',
                'verbose_name_plural': 'Equity Portfolios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.accountkeys',),
        ),
    ]
