# Generated by Django 5.1.1 on 2024-09-17 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("system_conf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        default="equity",
                        max_length=255,
                        unique=True,
                        verbose_name="Product",
                    ),
                ),
                ("symbol", models.CharField(max_length=255, verbose_name="Symbol")),
                (
                    "mode",
                    models.CharField(
                        choices=[("CE", "Call"), ("PE", "Put"), ("none", "N/A")],
                        default="none",
                        max_length=50,
                        verbose_name="MODE",
                    ),
                ),
                ("indicate", models.CharField(max_length=50, verbose_name="INDICATE")),
                ("type", models.CharField(max_length=50, verbose_name="TYPE")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("price", models.FloatField(verbose_name="PRICE")),
                ("stoploss", models.FloatField(verbose_name="STOPLOSS")),
                ("target", models.FloatField(verbose_name="TARGET")),
                (
                    "fixed_target",
                    models.FloatField(
                        blank=True, default=0, null=True, verbose_name="Fixed Target"
                    ),
                ),
                (
                    "profit",
                    models.FloatField(
                        blank=True, default=0, null=True, verbose_name="PROFIT (%)"
                    ),
                ),
                (
                    "max",
                    models.FloatField(
                        blank=True, default=0, null=True, verbose_name="MAX-P (%)"
                    ),
                ),
                ("max_l", models.FloatField(default=0, verbose_name="MAX-L (%)")),
                (
                    "highest_price",
                    models.FloatField(default=0, verbose_name="HIGHEST PRICE"),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True,
                        default="0",
                        max_length=255,
                        null=True,
                        verbose_name="ORDER ID",
                    ),
                ),
                ("order_status", models.TextField(verbose_name="ORDER STATUS")),
                ("lot", models.FloatField(verbose_name="LOT")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("CE", "Call"), ("PE", "Put"), ("none", "N/A")],
                        default="none",
                        max_length=50,
                        verbose_name="MODE",
                    ),
                ),
                ("price", models.FloatField(default=0, verbose_name="PRICE")),
                ("stoploss", models.FloatField(default=0, verbose_name="STOPLOSS")),
                ("target", models.FloatField(default=0, verbose_name="TARGET")),
                (
                    "fixed_target",
                    models.FloatField(
                        blank=True, default=0, null=True, verbose_name="Fixed Target"
                    ),
                ),
                ("max", models.FloatField(default=0, verbose_name="MAX GAIN")),
                ("max_l", models.FloatField(default=0, verbose_name="MAX LOSS")),
                (
                    "highest_price",
                    models.FloatField(default=0, verbose_name="HIGHEST PRICE"),
                ),
                ("lot", models.FloatField(default=0, verbose_name="Lots")),
                (
                    "order_id",
                    models.CharField(
                        blank=True,
                        default="0",
                        max_length=255,
                        null=True,
                        verbose_name="ORDER ID",
                    ),
                ),
                (
                    "order_status",
                    models.TextField(default="NONE", verbose_name="ORDER STATUS"),
                ),
                (
                    "tr_hit",
                    models.BooleanField(default=False, verbose_name="Target Hit"),
                ),
                (
                    "trailing_sl",
                    models.FloatField(default=0, verbose_name="Trailing SL"),
                ),
                (
                    "ltp",
                    models.FloatField(
                        blank=True, default=0, null=True, verbose_name="Ltp"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_conf.symbol",
                    ),
                ),
            ],
        ),
    ]
