# Generated by Django 5.1.1 on 2024-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="product",
            field=models.CharField(
                default="equity", max_length=255, verbose_name="Product"
            ),
        ),
    ]
