# Generated by Django 5.1.1 on 2024-10-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exchange',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Exchange'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Token'),
        ),
    ]
