# Generated by Django 5.1.1 on 2024-09-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_transaction_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Status",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stock.stockconfig",),
        ),
    ]
