# Generated by Django 5.1.1 on 2024-10-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_transaction_exchange_transaction_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockconfig',
            name='fno_activation',
            field=models.BooleanField(default=False),
        ),
    ]
