# Generated by Django 5.1.1 on 2024-10-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Name"
            ),
        ),
    ]
