# Generated by Django 5.1.1 on 2024-10-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockconfig_fno_activation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['product'], name='stock_trans_product_0e2037_idx'),
        ),
    ]
