# Generated by Django 5.1.1 on 2025-02-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_transaction_stock_trans_product_0e2037_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockconfig',
            name='capital_save',
            field=models.BooleanField(default=False, verbose_name='Capital Saved'),
        ),
        migrations.AddField(
            model_name='stockconfig',
            name='chart_price',
            field=models.FloatField(default=0, verbose_name='PRICE'),
        ),
    ]
