# Generated by Django 5.1.1 on 2024-10-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_transaction_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Status",
        ),
        migrations.CreateModel(
            name="Equity_Status",
            fields=[],
            options={
                "verbose_name": "Equity Status",
                "verbose_name_plural": "Equity Status",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stock.stockconfig",),
        ),
        migrations.CreateModel(
            name="FnO_Status",
            fields=[],
            options={
                "verbose_name": "FnO Status",
                "verbose_name_plural": "FnO Status",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stock.stockconfig",),
        ),
    ]
