# Generated by Django 5.1.1 on 2024-10-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_delete_status_equity_status_fno_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockconfig",
            name="stoploss_order_id",
            field=models.CharField(
                blank=True,
                default="0",
                max_length=255,
                null=True,
                verbose_name="SL ORDER ID",
            ),
        ),
        migrations.AddField(
            model_name="stockconfig",
            name="stoploss_order_placed",
            field=models.BooleanField(default=False, verbose_name="SL Ord Placed"),
        ),
        migrations.AddField(
            model_name="stockconfig",
            name="target_order_id",
            field=models.CharField(
                blank=True,
                default="0",
                max_length=255,
                null=True,
                verbose_name="Tr ORDER ID",
            ),
        ),
        migrations.AddField(
            model_name="stockconfig",
            name="target_order_placed",
            field=models.BooleanField(default=False, verbose_name="TR Ord Placed"),
        ),
    ]
