# Generated by Django 5.1.1 on 2025-02-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stockconfig_capital_save_stockconfig_chart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockconfig',
            name='chart_price',
            field=models.FloatField(default=0, verbose_name='CHART PRICE'),
        ),
    ]
