# Generated by Django 5.1.1 on 2024-10-04 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0006_stockconfig_stoploss_order_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equity_Transaction",
            fields=[],
            options={
                "verbose_name": "Equity Transaction",
                "verbose_name_plural": "Equity Transactions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stock.transaction",),
        ),
        migrations.CreateModel(
            name="FnO_Transaction",
            fields=[],
            options={
                "verbose_name": "FnO Transaction",
                "verbose_name_plural": "FnO Transactions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stock.transaction",),
        ),
    ]
