# Generated by Django 5.1.1 on 2025-04-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_stockconfig_chart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='chart_price',
            field=models.FloatField(default=0, verbose_name='Chart Price'),
        ),
    ]
