# Generated by Django 5.1.1 on 2025-04-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_transaction_chart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockconfig',
            name='entry_open_value',
            field=models.FloatField(default=0, verbose_name='Entry Open Value'),
        ),
    ]
