# Generated by Django 5.1.1 on 2025-04-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stockconfig_entry_open_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockconfig',
            name='entry_prev_close_value',
            field=models.FloatField(default=0, verbose_name='Entry Prev Close Value'),
        ),
    ]
