# Generated by Django 5.1.1 on 2025-05-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_stockconfig_entry_prev_close_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockconfig',
            name='manual_updated',
            field=models.BooleanField(default=False, verbose_name='Manual Updated'),
        ),
    ]
