# Generated by Django 5.1.1 on 2024-10-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='equity', max_length=255, unique=True, verbose_name='Product')),
                ('amount', models.FloatField(default=10000, verbose_name='Amount')),
                ('open_position', models.BigIntegerField(default=10, verbose_name='Open Position')),
                ('stoploss', models.FloatField(default=3, verbose_name='Stoploss(%)')),
                ('target', models.FloatField(default=4, verbose_name='Target(%)')),
                ('fixed_target', models.FloatField(default=4, verbose_name='Fixed TR(%)')),
                ('trail_stoploss_by', models.FloatField(default=5, verbose_name='Trail Stoploss By(%)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='equity', max_length=255, verbose_name='Product')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('symbol', models.CharField(max_length=100, unique=True, verbose_name='Symbol')),
                ('exchange', models.CharField(max_length=100, verbose_name='Exchange')),
                ('strike', models.BigIntegerField(blank=True, null=True, verbose_name='Strike')),
                ('token', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Token')),
                ('expiry', models.DateField(blank=True, null=True, verbose_name='Expiry')),
                ('lot', models.BigIntegerField(blank=True, null=True, verbose_name='Lots')),
                ('fno', models.BooleanField(default=False, verbose_name='FNO')),
                ('volume', models.FloatField(default=0, verbose_name='Volume')),
                ('oi', models.FloatField(default=0, verbose_name='Open Interest')),
                ('percentchange', models.FloatField(default=0, verbose_name='Change(%)')),
                ('valuechange', models.FloatField(default=0, verbose_name='Change(Value)')),
                ('ltp', models.FloatField(default=0, verbose_name='LTP')),
                ('weekhigh52', models.FloatField(default=0, verbose_name='52 Week High')),
                ('weeklow52', models.FloatField(default=0, verbose_name='52 Week Low')),
                ('nifty50', models.BooleanField(default=False)),
                ('nifty100', models.BooleanField(default=False)),
                ('nifty200', models.BooleanField(default=False)),
                ('midcpnifty50', models.BooleanField(default=False)),
                ('midcpnifty100', models.BooleanField(default=False)),
                ('midcpnifty150', models.BooleanField(default=False)),
                ('smallcpnifty50', models.BooleanField(default=False)),
                ('smallcpnifty100', models.BooleanField(default=False)),
                ('smallcpnifty250', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
