# Generated by Django 5.0.6 on 2024-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField(default=4000, verbose_name="AMOUNT")),
                (
                    "place_order",
                    models.BooleanField(
                        default=False, verbose_name="Activate Order Placement"
                    ),
                ),
                ("buy_market_order", models.BooleanField(default=False)),
                ("sell_market_order", models.BooleanField(default=True)),
                (
                    "daily_max_profit",
                    models.FloatField(default=0, verbose_name="Daily Max-Profit"),
                ),
                ("daily_max_profit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "daily_max_loss",
                    models.FloatField(default=0, verbose_name="Daily Max-Loss"),
                ),
                ("daily_max_loss_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
