# Generated by Django 5.1.1 on 2024-09-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        default="equity",
                        max_length=255,
                        unique=True,
                        verbose_name="Product",
                    ),
                ),
                (
                    "place_order",
                    models.BooleanField(default=False, verbose_name="Place Order"),
                ),
                ("amount", models.FloatField(default=10000, verbose_name="Amount")),
                (
                    "open_position",
                    models.BigIntegerField(default=10, verbose_name="Open Position"),
                ),
                ("stoploss", models.FloatField(default=3, verbose_name="Stoploss(%)")),
                ("target", models.FloatField(default=4, verbose_name="Target(%)")),
                (
                    "fixed_target",
                    models.FloatField(default=4, verbose_name="Fixed TR(%)"),
                ),
                (
                    "trail_stoploss_by",
                    models.FloatField(default=5, verbose_name="Trail Stoploss By(%)"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        default="equity",
                        max_length=255,
                        unique=True,
                        verbose_name="Product",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "symbol",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Symbol"
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Exchange"
                    ),
                ),
                (
                    "strike",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Strike"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Token"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="Expiry Date"),
                ),
                (
                    "lot",
                    models.BigIntegerField(blank=True, null=True, verbose_name="Lots"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
