# Generated by Django 5.1.1 on 2024-10-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_conf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='pivot',
            field=models.FloatField(default=0, verbose_name='Pivot'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='r1',
            field=models.FloatField(default=0, verbose_name='R1'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='r2',
            field=models.FloatField(default=0, verbose_name='R2'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='r3',
            field=models.FloatField(default=0, verbose_name='R3'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='s1',
            field=models.FloatField(default=0, verbose_name='S1'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='s2',
            field=models.FloatField(default=0, verbose_name='S2'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='s3',
            field=models.FloatField(default=0, verbose_name='S3'),
        ),
    ]
