# Generated by Django 5.0.6 on 2024-06-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_conf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="daily_fixed_stoploss",
            field=models.FloatField(default=0, verbose_name="Daily Fixed SL"),
        ),
    ]
