# Generated by Django 5.1.1 on 2024-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_conf", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="symbol",
            name="expiry_date",
        ),
        migrations.AddField(
            model_name="symbol",
            name="expiry",
            field=models.DateField(blank=True, null=True, verbose_name="Expiry"),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="exchange",
            field=models.CharField(max_length=100, verbose_name="Exchange"),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="product",
            field=models.CharField(
                default="equity", max_length=255, verbose_name="Product"
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Token"
            ),
        ),
    ]
