# Generated by Django 5.1.1 on 2024-09-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_conf", "0002_remove_symbol_expiry_date_symbol_expiry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symbol",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
    ]
