# Generated by Django 5.1.1 on 2024-10-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_conf', '0002_symbol_pivot_symbol_r1_symbol_r2_symbol_r3_symbol_s1_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='configuration',
            index=models.Index(fields=['product'], name='system_conf_product_bc42ad_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['-fno'], name='system_conf_fno_67ea0f_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['exchange'], name='system_conf_exchang_d34a32_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['product'], name='system_conf_product_dcddff_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['-nifty50'], name='system_conf_nifty50_b1596a_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['-nifty100'], name='system_conf_nifty10_d1ad17_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['-nifty200'], name='system_conf_nifty20_f9407c_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['-midcpnifty50'], name='system_conf_midcpni_bca8ad_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['-midcpnifty100'], name='system_conf_midcpni_71a046_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['-midcpnifty150'], name='system_conf_midcpni_24bac3_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['-smallcpnifty50'], name='system_conf_smallcp_582837_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['-smallcpnifty100'], name='system_conf_smallcp_8c65f3_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['-smallcpnifty250'], name='system_conf_smallcp_13a4f2_idx'),
        ),
    ]
