# Generated by Django 5.1.1 on 2024-09-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_conf", "0003_alter_symbol_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbol",
            name="fno",
            field=models.BooleanField(default=False, verbose_name="FNO"),
        ),
    ]
