# Generated by Django 5.1.1 on 2024-10-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_conf', '0003_configuration_system_conf_product_bc42ad_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='midcpnifty100',
            field=models.BooleanField(default=False, verbose_name='MidCP100'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='midcpnifty150',
            field=models.BooleanField(default=False, verbose_name='MidCP150'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='midcpnifty50',
            field=models.BooleanField(default=False, verbose_name='MidCP50'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='nifty100',
            field=models.BooleanField(default=False, verbose_name='Nifty100'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='nifty200',
            field=models.BooleanField(default=False, verbose_name='Nifty200'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='nifty50',
            field=models.BooleanField(default=False, verbose_name='Nifty50'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='smallcpnifty100',
            field=models.BooleanField(default=False, verbose_name='SmallCP100'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='smallcpnifty250',
            field=models.BooleanField(default=False, verbose_name='SmallCP250'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='smallcpnifty50',
            field=models.BooleanField(default=False, verbose_name='SmallCP50'),
        ),
    ]
