# Generated by Django 5.1.1 on 2025-02-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_conf', '0004_alter_symbol_midcpnifty100_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='month_pivot',
            field=models.FloatField(default=0, verbose_name='Month-Pivot'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='month_r1',
            field=models.FloatField(default=0, verbose_name='Month-R1'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='month_r2',
            field=models.FloatField(default=0, verbose_name='Month-R2'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='month_r3',
            field=models.FloatField(default=0, verbose_name='Month-R3'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='month_s1',
            field=models.FloatField(default=0, verbose_name='Month-S1'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='month_s2',
            field=models.FloatField(default=0, verbose_name='Month-S2'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='month_s3',
            field=models.FloatField(default=0, verbose_name='Month-S3'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='week_pivot',
            field=models.FloatField(default=0, verbose_name='Week-Pivot'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='week_r1',
            field=models.FloatField(default=0, verbose_name='Week-R1'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='week_r2',
            field=models.FloatField(default=0, verbose_name='Week-R2'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='week_r3',
            field=models.FloatField(default=0, verbose_name='Week-R3'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='week_s1',
            field=models.FloatField(default=0, verbose_name='Week-S1'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='week_s2',
            field=models.FloatField(default=0, verbose_name='Week-S2'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='week_s3',
            field=models.FloatField(default=0, verbose_name='Week-S3'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='pivot',
            field=models.FloatField(default=0, verbose_name='DAY-Pivot'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='r1',
            field=models.FloatField(default=0, verbose_name='DAY-R1'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='r2',
            field=models.FloatField(default=0, verbose_name='DAY-R2'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='r3',
            field=models.FloatField(default=0, verbose_name='DAY-R3'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='s1',
            field=models.FloatField(default=0, verbose_name='DAY-S1'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='s2',
            field=models.FloatField(default=0, verbose_name='DAY-S2'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='s3',
            field=models.FloatField(default=0, verbose_name='DAY-S3'),
        ),
    ]
