# Generated by Django 5.1.1 on 2024-09-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_conf", "0004_symbol_fno"),
    ]

    operations = [
        migrations.AddField(
            model_name="symbol",
            name="ltp",
            field=models.FloatField(default=0, verbose_name="LTP"),
        ),
        migrations.AddField(
            model_name="symbol",
            name="oi",
            field=models.FloatField(default=0, verbose_name="Open Interest"),
        ),
        migrations.AddField(
            model_name="symbol",
            name="percentchange",
            field=models.FloatField(default=0, verbose_name="Change(%)"),
        ),
        migrations.AddField(
            model_name="symbol",
            name="valuechange",
            field=models.FloatField(default=0, verbose_name="Change(Value)"),
        ),
        migrations.AddField(
            model_name="symbol",
            name="volume",
            field=models.FloatField(default=0, verbose_name="Volume"),
        ),
        migrations.AddField(
            model_name="symbol",
            name="weekhigh52",
            field=models.FloatField(default=0, verbose_name="52 Week High"),
        ),
        migrations.AddField(
            model_name="symbol",
            name="weeklow52",
            field=models.FloatField(default=0, verbose_name="52 Week Low"),
        ),
    ]
