# Generated by Django 5.1.1 on 2025-05-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_conf', '0006_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('oi_915', models.FloatField(default=0, verbose_name='9:15')),
                ('oi_930', models.FloatField(default=0, verbose_name='9:30')),
                ('oi_945', models.FloatField(default=0, verbose_name='9:45')),
                ('oi_10', models.FloatField(default=0, verbose_name='10:00')),
                ('oi_1015', models.FloatField(default=0, verbose_name='10:15')),
                ('oi_1030', models.FloatField(default=0, verbose_name='10:30')),
                ('oi_1045', models.FloatField(default=0, verbose_name='10:45')),
                ('oi_11', models.FloatField(default=0, verbose_name='11:00')),
                ('oi_1115', models.FloatField(default=0, verbose_name='11:15')),
                ('oi_1130', models.FloatField(default=0, verbose_name='11:30')),
                ('oi_1145', models.FloatField(default=0, verbose_name='11:45')),
                ('oi_12', models.FloatField(default=0, verbose_name='12:00')),
                ('oi_1215', models.FloatField(default=0, verbose_name='12:15')),
                ('oi_1230', models.FloatField(default=0, verbose_name='12:30')),
                ('oi_1245', models.FloatField(default=0, verbose_name='12:45')),
                ('oi_13', models.FloatField(default=0, verbose_name='13:00')),
                ('oi_1315', models.FloatField(default=0, verbose_name='13:15')),
                ('oi_1330', models.FloatField(default=0, verbose_name='13:30')),
                ('oi_1345', models.FloatField(default=0, verbose_name='13:45')),
                ('oi_14', models.FloatField(default=0, verbose_name='14:00')),
                ('oi_1415', models.FloatField(default=0, verbose_name='14:15')),
                ('oi_1430', models.FloatField(default=0, verbose_name='14:30')),
                ('oi_1445', models.FloatField(default=0, verbose_name='14:45')),
                ('oi_15', models.FloatField(default=0, verbose_name='15:00')),
                ('oi_1515', models.FloatField(default=0, verbose_name='15:15')),
                ('oi_1530', models.FloatField(default=0, verbose_name='15:30')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
