# Generated by Django 5.1.1 on 2025-05-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_conf', '0007_oichange'),
    ]

    operations = [
        migrations.AddField(
            model_name='oichange',
            name='oi',
            field=models.FloatField(default=0, verbose_name='OI%'),
        ),
    ]
