"""
Django settings for trade_bros project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-kt0o0ru3ij04$4a*c4g%rvjo3%q5tzk&k#(60b@2c3yej96g-g"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "1").lower() in ["true", "t", "1"]

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "https://trade-bros.onrender.com,https://localhost:8000,https://127.0.0.1:8000").split(",")

BED_URL_DOMAIN = os.getenv("CSRF_TRUSTED_ORIGINS", "https://trade-bros.onrender.com")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "admin_extra_buttons",
    "import_export",
    
    "logs",
    "option",
    "system_conf",
    "dashboard",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "trade_bros.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "trade_bros.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse("postgresql://trade_bros_xrie_user:ojB5nvjOdmlI6ubxEXTzVp1csuyCr4NH@dpg-cqb5h9aj1k6c73allb3g-a/trade_bros_xrie", conn_max_age=600),
} if os.getenv("SERVER_DB", True) else {
    "default": dj_database_url.parse("postgresql://trade_bros_xrie_user:ojB5nvjOdmlI6ubxEXTzVp1csuyCr4NH@dpg-cqb5h9aj1k6c73allb3g-a.virginia-postgres.render.com/trade_bros_xrie", conn_max_age=600),
}

# DATABASES = {
#     "default": dj_database_url.parse("postgres://tradebros_ffv6_user:XLeQuTKte7aoyvQa5TOlWWf885tCGu4v@dpg-cpfnnartg9os73bhumqg-a.virginia-postgres.render.com/tradebros_ffv6", conn_max_age=600),
# } if os.getenv("SERVER_DB", True) else {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True
USE_L10N = False

DATETIME_FORMAT = "N j, Y, g:i:s a"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Telegram Configuration
TELEGRAM_APP_ID = '29604910'
TELEGRAM_HASH_ID = 'a1645f10ee4abaf7ef0ebe4038fe5137'
TELEGRAM_BOT = '7040073287:AAGO4tJeGsRCCALtMyXepttn_uLlI3nqJdk'