# Generated by Django 5.0.6 on 2024-06-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Keys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broker_name",
                    models.CharField(max_length=200, verbose_name="Broker name"),
                ),
                (
                    "username",
                    models.CharField(
                        default="please_enter_user_name",
                        max_length=200,
                        unique=True,
                        verbose_name="UserName",
                    ),
                ),
                (
                    "api_key",
                    models.TextField(blank=True, null=True, verbose_name="Api Key"),
                ),
                (
                    "secret_key",
                    models.TextField(
                        blank=True, null=True, verbose_name="Api Secret Key"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Account Id"
                    ),
                ),
                (
                    "user_password",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Account Password",
                    ),
                ),
                (
                    "user_pin",
                    models.CharField(
                        blank=True,
                        default="please_enter_user_pin",
                        max_length=50,
                        null=True,
                        verbose_name="Pin",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True,
                        default="please_enter_user_accesstoken",
                        null=True,
                        verbose_name="Access Token",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
