# Generated by Django 5.0.6 on 2024-06-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("option", "0002_dailyrecord_index_transaction_optionsymbol_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyrecord",
            name="expiry_index",
        ),
    ]
