# Generated by Django 5.0.6 on 2024-06-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("option", "0003_remove_dailyrecord_expiry_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="index",
            name="chain_strike_price_diff",
            field=models.FloatField(
                default=0, verbose_name="Chain Strike Price Difference"
            ),
        ),
    ]
