# Generated by Django 5.0.6 on 2024-06-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("option", "0003_remove_dailyrecord_expiry_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Status",
                "verbose_name_plural": "Daily Status",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Status",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("option.stockconfig",),
        ),
    ]
