# Generated by Django 5.0.6 on 2024-06-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Log Name"
                    ),
                ),
                ("log_desc", models.TextField(verbose_name="Log Desc")),
                ("error", models.BooleanField(default=False, verbose_name="Error")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
